name: CrickNova_Ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  google_fonts: ^6.2.1

  # CAMERA (for Live Match)
  camera: ^0.11.0+1

  flutter_tts: ^3.6.3
  speech_to_text: ^7.3.0
  animated_text_kit: ^4.2.2
  image: ^4.1.3
  file_picker: ^10.3.7
  http: ^1.6.0
  video_player: ^2.8.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
  google_sign_in: ^6.2.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.0 
  flutter_cashfree_pg_sdk: ^2.1.6
  razorpay_flutter: ^1.4.0
  url_launcher: ^6.3.2
  in_app_purchase: ^3.1.13
  android_intent_plus: ^5.3.0
  app_links: ^6.0.0
  webview_flutter: ^4.7.0
  # GRAPH
  fl_chart: ^1.1.1
  flutter_native_splash: ^2.4.7
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/